stages:
  - test
  #- clean
  - build
  - deploy
unit-test:
  stage: test
  script:
    - 'echo "Running test cases"'
    # - /home/shenoys/Unity-2022.1.12f1/Editor/Unity -nographics -quit -batchmode -projectPath . -runTests -testPlatform playmode -testResults "./Results/TestResult.xml"
    - '& "C:\Program Files\Unity\Hub\Editor\2021.3.17f1\Editor\Unity.exe" \
      -quit \
      -batchmode \
      -projectPath . \
      -runTests \
      -testPlatform playmode \
      -logFile "test_output.txt" \
      -testResults "./unit-tests.xml"'
    
# unity-clean:
#   stage: clean
#   script:
#     - 'echo "Removing existing build directory..'
#     - 'rmdir -Force -Recurse "./Builds/WebGL"'
unity-build:
  stage: build
  script:
    - 'echo "Building..."'
    # - /home/shenoys/Unity-2022.1.12f1/Editor/Unity -nographics -quit -batchmode -projectPath . -runTests -testPlatform playmode -logFile "./Logs/[Log]_Build.txt" \
    #   buildTarget WebGL -outputPath ./Builds/WebGL -executeMethod CommandLineBuilder.BuildWebGLApplication -manualLicenseFile /home/shenoys/UnityLic.ulf
    - '& "C:\Program Files\Unity\Hub\Editor\2021.3.17f1\Editor\Unity.exe" \
      -quit \
      -batchmode \
      -projectPath ".\" \
      -logFile "build_output.txt" \
      -buildTarget WebGL \
      -outputPath ".\Builds\WebGL" \
      -executeMethod CommandLineBuilder.BuildWebGLApplication'
playstore:
  stage: deploy
  script: echo 'Deploying...'